# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Player Library

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g @angular/cli
      - run: npm install
      - run: ng build ngx-audioplayer --prod
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          package: ./dist/ngx-audioplayer
          token: ${{ secrets.NPM_TOKEN }}

